services:
  - type: web
    name: sendit-api
    runtime: python
    repo: https://github.com/hnferdinard/sendit-api
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: MAX_UPLOAD_SIZE
        value: 5242880
      - key: WEATHER_API_URL
        value: https://api.open-meteo.com/v1/forecast
