services:
  - type: web
    name: sendit-api
    runtime: python
    repo: https://github.com/hnferdinard/sendit-api
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
